docs/spring2021/index.md
This micro-change removes an extra `every Monday`. 😇
=> Remove duplicated text

docs/spring2021/projects.md
Update Scancer project with the below changes:
1.  Daniel's Linkedin URL
2. Daniel's Video (ML part of the Scancer project)
=> Update Scancer with Daniel Linkedin + Daniel Video (ML part)

docs/spring2021/projects.md
For the Intel Scene Classification project:
* Adding Linkedin profiles
* Adding report URL
=> Updating project description

docs/spring2021/panel.md, docs/spring2021/projects.md
This PR links my name to my website.
=> Link project author to homepage

docs/cloud-gpus/cloud-gpus.csv
Pricing information: https://datacrunch.io/products
=> Added DataCrunch.io GPUs

docs/cloud-gpus/cloud-gpus.csv
Recently updated the prices of A100s: https://datacrunch.io/products
=> updated A100 prices

docs/course/2022/project-showcase/index.md
=> Name error (it was only one name) + Adding Twitter

docs/course/2022/project-showcase/index.md
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>
=> Update geolocator entry

docs/course/2022/project-showcase/index.md
=> Update index.md (add name to Recipewise)

docs/course/2022/project-showcase/index.md
=> add team44 links

docs/course/2022/project-showcase/index.md
Added working demo link for board game rules explainer
=> add working demo link

docs/course/2022/project-showcase/index.md
Changed entry of `Landcover Segmentation` --> added a link to the name
=> Update index.md for change in Landcover Segmentation entry

docs/cloud-gpus/serverless-gpus.csv
Include the DeepInfra's serverless GPU service to the list Also fix the A100 GPU architecture
=> Add DeepInfra to the serverless section.

docs/cloud-gpus/index.md, docs/cloud-gpus/serverless-gpus.csv
removes extra row, adds baseten a100s
=> Updates serverless-gpus and cloud-gpus

docs/cloud-gpus/cloud-gpus.csv
Adding Cloud GPUs available on https://www.cudocompute.com
=> Update cloud-gpus.csv with Cudo Compute

docs/cloud-gpus/cloud-gpus.csv
=> Fixes GPU type for AWS T4 (16 GB)

docs/llm-bootcamp/index.md
so people can directly see and reach out to them on social media
=> update Instructor Team contact links

mkdocs.yml
Fix YouTube link in mkdocs.yml
=> Fix YouTube link in mkdocs.yml

docs/cloud-gpus/cloud-gpus.csv
Hi,
I work for Latitude.sh, we've updated our prices.
Can you update please?
=> Update Latitude.sh prices on cloud-gpus.csv

docs/llm-bootcamp/spring-2023/askfsdl-walkthrough/chapter_summaries.md
fix typos in askfsdl-walkthrough
=> fix typos in askfsdl-walkthrough

docs/cloud-gpus/cloud-gpus.csv
cf discussion on Twitter here: Oracle Cloud is competitive!
=> adds Oracle cloud, fixes typo

docs/cloud-gpus/cloud-gpus.csv
Hello, I worked for latitude and we have included and updated our GPU plans, so can you update it as well?
[Latitude.sh gpu pricing](https://www.latitude.sh/accelerate/pricing)
=> Update Latitude.sh GPUs

docs/cloud-gpus/serverless-gpus.csv
According to Pricing in below page 
https://www.inferless.com/pricing
=> Adding Inferless Pricing for Serverless GPUs

docs/cloud-gpus/cloud-gpus.csv
From https://www.novonimbus.com/gpu-pricing
=> Add NovoNimbus cloud offerings

docs/cloud-gpus/cloud-gpus.csv, docs/cloud-gpus/index.md, docs/cloud-gpus/serverless-gpus.csv
- Price update
- New Cloud SKU
- Serverless SKU
=> OVHcloud update

docs/llm-bootcamp/spring-2023/index.md
`href` attribute of `video-card` for **Harrison Chase: Agents** talk was wrong
=> fix "chase-agents" video-card href
